shell=$(basename "$SHELL")
BLUE="\033[34m"
RESETC="\033[0m"


echo "====================================="
echo " "
echo " Welcome back, $USER"
echo " "
echo "====================================="
echo " "
printf "${BLUE}Current time: ${RESETC}" 
echo "$(date +%H:%M)"
printf "${BLUE}Current date: ${RESETC}" 
echo "$(date +"%A %B %d")"
printf "${BLUE}Hostname:${RESETC} $(hostname)"
echo " "
printf "${BLUE}Current dir:${RESETC} $(pwd)"
echo " "
printf "${BLUE}Shell:${RESETC} %s\n" "$shell"
printf "${BLUE}Kernel version: ${RESETC}"
uname -r
echo " "
printf "%b${BLUE}Memory usage:${RESETC} $(free -h)\n"
echo " "
echo  "${BLUE}Disk usage:${RESETC} $(df -h)"
echo " "
echo "${BLUE}Uptime:${RESETC} " "$(uptime)"
echo "========================================"
